/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;

/**
 *
 * @author Administrator
 */
public class FrMain extends javax.swing.JFrame {

    /**
     * Creates new form FrMain
     */
    public FrMain() {
        initComponents();
        pnLeft.setPreferredSize(new Dimension(260, HEIGHT));
        pnLeft.setMinimumSize(new Dimension(240, HEIGHT));
        pnLeft.setMaximumSize(new Dimension(300, HEIGHT));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTop = new javax.swing.JPanel();
        pnThongTin = new javax.swing.JPanel();
        pnDangNhap = new javax.swing.JPanel();
        lbXinChao = new javax.swing.JLabel();
        lbKhachHang = new javax.swing.JLabel();
        btDangNhap = new javax.swing.JButton();
        pnCenter = new javax.swing.JPanel();
        splitCenter = new javax.swing.JSplitPane();
        pnLeft = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        pnRight = new javax.swing.JPanel();
        tabbed = new javax.swing.JTabbedPane();
        pnQuanLyCongDan = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnBottom = new javax.swing.JPanel();
        pnCopyRight = new javax.swing.JPanel();
        lbCopy = new javax.swing.JLabel();
        pnThoiGian = new javax.swing.JPanel();
        lbTime = new javax.swing.JLabel();
        lbThoiGian = new javax.swing.JLabel();
        mnbTieuDe = new javax.swing.JMenuBar();
        mnTrangChu = new javax.swing.JMenu();
        mnQuanLyCongDan = new javax.swing.JMenu();
        mnQuanLyTienAnTienSu = new javax.swing.JMenu();
        mnQuanLyHonNhan = new javax.swing.JMenu();
        mnThongKe = new javax.swing.JMenu();
        mnQuanLyNhanSu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HỆ THỐNG QUẢN LÝ HỒ SƠ CÔNG DÂN ĐIỆN TỬ");

        pnTop.setLayout(new java.awt.BorderLayout());

        pnThongTin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 1));
        pnThongTin.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        pnTop.add(pnThongTin, java.awt.BorderLayout.WEST);

        pnDangNhap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        pnDangNhap.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 15, 5));

        lbXinChao.setText("Xin chào: ");
        pnDangNhap.add(lbXinChao);

        lbKhachHang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbKhachHang.setText("<html><a href=\"\" title=\"\">Khách Hàng</a><html>");
        lbKhachHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnDangNhap.add(lbKhachHang);

        btDangNhap.setText("Đăng Nhập");
        pnDangNhap.add(btDangNhap);

        pnTop.add(pnDangNhap, java.awt.BorderLayout.EAST);

        getContentPane().add(pnTop, java.awt.BorderLayout.PAGE_START);

        pnCenter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        pnCenter.setLayout(new java.awt.BorderLayout());

        splitCenter.setDividerSize(10);
        splitCenter.setOneTouchExpandable(true);

        pnLeft.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 6), javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Phường", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 153, 0))), "Phường", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 153, 0))); // NOI18N
        pnLeft.setMinimumSize(new java.awt.Dimension(160, 0));
        pnLeft.setPreferredSize(new java.awt.Dimension(160, 282));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hòa Khánh Bắc", "Hòa Khánh Nam", "Hòa Hiệp" }));

        javax.swing.GroupLayout pnLeftLayout = new javax.swing.GroupLayout(pnLeft);
        pnLeft.setLayout(pnLeftLayout);
        pnLeftLayout.setHorizontalGroup(
            pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, 0, 113, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnLeftLayout.setVerticalGroup(
            pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        splitCenter.setLeftComponent(pnLeft);

        pnRight.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 6, 1, 1), javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Task Quản Lý", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 153, 0)))); // NOI18N

        tabbed.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout pnQuanLyCongDanLayout = new javax.swing.GroupLayout(pnQuanLyCongDan);
        pnQuanLyCongDan.setLayout(pnQuanLyCongDanLayout);
        pnQuanLyCongDanLayout.setHorizontalGroup(
            pnQuanLyCongDanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnQuanLyCongDanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnQuanLyCongDanLayout.setVerticalGroup(
            pnQuanLyCongDanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnQuanLyCongDanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbed.addTab("Quản Lý Công Dân", pnQuanLyCongDan);

        javax.swing.GroupLayout pnRightLayout = new javax.swing.GroupLayout(pnRight);
        pnRight.setLayout(pnRightLayout);
        pnRightLayout.setHorizontalGroup(
            pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRightLayout.createSequentialGroup()
                .addComponent(tabbed)
                .addContainerGap())
        );
        pnRightLayout.setVerticalGroup(
            pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRightLayout.createSequentialGroup()
                .addComponent(tabbed)
                .addContainerGap())
        );

        splitCenter.setRightComponent(pnRight);

        pnCenter.add(splitCenter, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnCenter, java.awt.BorderLayout.CENTER);

        pnBottom.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        pnBottom.setLayout(new java.awt.BorderLayout());

        lbCopy.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lbCopy.setText("<html><b> Copy right  &copy;  13T4  BKTeam  <b></html>");
        pnCopyRight.add(lbCopy);

        pnBottom.add(pnCopyRight, java.awt.BorderLayout.CENTER);

        pnThoiGian.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnThoiGian.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        lbTime.setText("Thời gian: ");
        pnThoiGian.add(lbTime);

        lbThoiGian.setText("10:30 PM 13/04/2017");
        pnThoiGian.add(lbThoiGian);

        pnBottom.add(pnThoiGian, java.awt.BorderLayout.EAST);

        getContentPane().add(pnBottom, java.awt.BorderLayout.PAGE_END);

        mnTrangChu.setText("TRANG CHỦ");
        mnbTieuDe.add(mnTrangChu);

        mnQuanLyCongDan.setText("||  QUẢNG LÝ CÔNG DÂN");
        mnbTieuDe.add(mnQuanLyCongDan);

        mnQuanLyTienAnTienSu.setText("||  QUẢNG LÝ TIỀN ÁN TIỀN SỰ");
        mnbTieuDe.add(mnQuanLyTienAnTienSu);

        mnQuanLyHonNhan.setText("||  QUẢNG LÝ HÔN NHÂN");
        mnbTieuDe.add(mnQuanLyHonNhan);

        mnThongKe.setText("||  THỐNG KÊ");
        mnbTieuDe.add(mnThongKe);

        mnQuanLyNhanSu.setText("||  QUẢNG LÝ NHÂN SỰ");
        mnbTieuDe.add(mnQuanLyNhanSu);

        setJMenuBar(mnbTieuDe);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDangNhap;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbCopy;
    private javax.swing.JLabel lbKhachHang;
    private javax.swing.JLabel lbThoiGian;
    private javax.swing.JLabel lbTime;
    private javax.swing.JLabel lbXinChao;
    private javax.swing.JMenu mnQuanLyCongDan;
    private javax.swing.JMenu mnQuanLyHonNhan;
    private javax.swing.JMenu mnQuanLyNhanSu;
    private javax.swing.JMenu mnQuanLyTienAnTienSu;
    private javax.swing.JMenu mnThongKe;
    private javax.swing.JMenu mnTrangChu;
    private javax.swing.JMenuBar mnbTieuDe;
    private javax.swing.JPanel pnBottom;
    private javax.swing.JPanel pnCenter;
    private javax.swing.JPanel pnCopyRight;
    private javax.swing.JPanel pnDangNhap;
    private javax.swing.JPanel pnLeft;
    private javax.swing.JPanel pnQuanLyCongDan;
    private javax.swing.JPanel pnRight;
    private javax.swing.JPanel pnThoiGian;
    private javax.swing.JPanel pnThongTin;
    private javax.swing.JPanel pnTop;
    private javax.swing.JSplitPane splitCenter;
    private javax.swing.JTabbedPane tabbed;
    // End of variables declaration//GEN-END:variables
}
